name: VolleyBall
version: 1.1.4
description: Simple volleyball game plugin
author: Jeremaster101
main: jeremynoesen.volleyball.VolleyBall
api-version: 1.13
depend: [WorldEdit]
commands:
  volleyball:
    description: Main VolleyBall command. For more, type /volleyball help
    usage: /<command>
    aliases: [vb]
