name: VolleyBall
version: 1.2.0
description: Simple volleyball game plugin
author: Jeremaster101
main: xyz.jeremynoesen.volleyball.VolleyBall
api-version: 1.13
commands:
  volleyball:
    description: Main VolleyBall command. For more, type /volleyball help
    usage: /<command>
    aliases: [vb]
