name: VolleyBall
version: 1.1.2
description: Simple volleyball game plugin
author: Jeremaster101
main: jndev.volleyball.VolleyBall
api-version: 1.13
depends: [WorldEdit]
commands:
  volleyball:
    description: Main VolleyBall command. For more, type /volleyball help
    usage: /<command>
